### ISSUE TITLE
Swatch images

### ISSUE THREAD

**Issue by gabrielwinnberg** [wp-premium/woocommerce-variation-swatches-and-photos#1]
Hello,

This is a great plugin so thanks!

When I export a number of variations it seems the the image references are stored in the parent product. Am I correct? That makes it difficult to batch import images. I have two suggestions:

1. Allow type "variation image" apart from custom and taxonomy images. Seems simple and logical.
2. Place image reference in child product.

**Comment by gabrielwinnberg** [comment]
Also, it doesn't load the 32x32 swatch thumbs but the full size images which happen to be 2600x2600. So neither the admin page nor the front-end product page can be loaded. In this case the site in question sells paint, so each product can have up to 300 different colors (plus different sizes).

**Comment by remcotolsma** [comment]
This repository is just a mirror of the WooCommerce Variation Swatches and Photos plugin. Please don't open issues, you should contact the WooCommerce help desk for issues » https://www.woocommerce.com/my-account/tickets/.
